# Generated by Django 5.2.2 on 2025-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('objective', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_rate', models.FloatField()),
                ('budget', models.IntegerField()),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('complete', 'Complete'), ('at_risk', 'At Risk'), ('delayed', 'Delayed')], default='on_track')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
